services:

    silex.app:
      class: Silex\Application
    database:
          class: Services\Database
          arguments: ['@silex.app','@service_container']
    mapper.foo:
      class: Services\Mapper\FooMapper
      arguments: ['@silex.app','@service_container']
